#!/usr/bin/env bash
# shellcheck disable=SC2086
set -e

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Counters
PASSED=0
FAILED=0

# Helper functions
check_pass() {
  echo -e "${GREEN}✓${NC} $1"
  ((PASSED++))
}

check_fail() {
  echo -e "${RED}✗${NC} $1"
  ((FAILED++))
}

check_warn() {
  echo -e "${YELLOW}⚠${NC} $1"
}

echo "🏥 Agentic Hybrid Search - System Health Check"
echo "=============================================="
echo ""

# 1. Docker
if docker info > /dev/null 2>&1; then
  check_pass "Docker running"
else
  check_fail "Docker not running — run 'docker compose up -d' from repo root"
fi

# 2. Python version (require 3.13+)
PYTHON_VERSION=$(python3 --version 2>&1 | awk '{print $2}')
if [[ "$PYTHON_VERSION" =~ ^3\.1[3-9] ]] || [[ "$PYTHON_VERSION" =~ ^3\.[2-9][0-9] ]]; then
  check_pass "Python 3.13+ ($PYTHON_VERSION)"
else
  check_fail "Python 3.13+ required (found $PYTHON_VERSION) — see CLAUDE.md for setup"
fi

# 3. Node version (require 24+)
if command -v node > /dev/null 2>&1; then
  NODE_VERSION=$(node --version 2>&1 | sed 's/v//')
  NODE_MAJOR=$(echo $NODE_VERSION | cut -d. -f1)
  if [ "$NODE_MAJOR" -ge 24 ]; then
    check_pass "Node 24+ ($NODE_VERSION)"
  else
    check_fail "Node 24+ required (found $NODE_VERSION) — install from nodejs.org or nvm"
  fi
else
  check_fail "Node.js not installed — required for frontend; install from nodejs.org"
fi

# 4. .env file with GOOGLE_API_KEY
if [ -f .env ] && grep -q "^GOOGLE_API_KEY=" .env && [ -n "$(grep '^GOOGLE_API_KEY=' .env | cut -d= -f2)" ]; then
  check_pass "GOOGLE_API_KEY set in .env"
else
  check_fail "GOOGLE_API_KEY missing in .env — get key from aistudio.google.com/apikey"
fi

# 5. .env file with LOGIN_PASSWORD
if [ -f .env ] && grep -q "^LOGIN_PASSWORD=" .env && [ -n "$(grep '^LOGIN_PASSWORD=' .env | cut -d= -f2)" ]; then
  check_pass "LOGIN_PASSWORD set in .env"
else
  check_warn "LOGIN_PASSWORD missing in .env — will be auto-generated by setup.sh"
fi

# 6. OpenSearch reachable
if curl -sf http://localhost:9200 > /dev/null 2>&1; then
  check_pass "OpenSearch reachable (http://localhost:9200)"
else
  check_fail "OpenSearch not reachable — run 'docker compose up -d' from repo root"
fi

# 7. PostgreSQL reachable
if pg_isready -h localhost -p 5432 > /dev/null 2>&1; then
  check_pass "PostgreSQL reachable (localhost:5432)"
else
  check_fail "PostgreSQL not reachable — run 'docker compose up -d' from repo root"
fi

# 8. .venv exists
if [ -d ".venv" ] && [ -f ".venv/bin/python" ]; then
  check_pass ".venv/ exists with Python executable"
else
  check_fail ".venv/ not found or incomplete — run 'make setup' or './scripts/setup.sh'"
fi

# 9. npm deps installed (web/)
if [ -d "web/node_modules" ]; then
  check_pass "npm dependencies installed (web/node_modules)"
else
  check_fail "npm dependencies missing — run 'make install-web' or 'npm install' in web/"
fi

echo ""
echo "=============================================="
echo "Summary: ${GREEN}$PASSED passed${NC}, ${RED}$FAILED failed${NC}"
echo ""

if [ $FAILED -eq 0 ]; then
  echo -e "${GREEN}✅ System is healthy. Ready to develop!${NC}"
  echo ""
  echo "Next steps:"
  echo "  • Backend:  make dev-api    (http://localhost:8000)"
  echo "  • Frontend: make dev-web    (http://localhost:5173)"
  echo "  • Both:     make dev        (starts both, backend in background)"
  exit 0
else
  echo -e "${RED}❌ System checks failed. See errors above.${NC}"
  echo ""
  echo "Quick fixes:"
  echo "  • Docker:       docker compose up -d         (from repo root)"
  echo "  • Python 3.13+: see CLAUDE.md setup section"
  echo "  • Node 24+:     brew install node  OR  nvm install 24"
  echo "  • .venv:        ./scripts/setup.sh  OR  make setup"
  echo ""
  echo "Full setup: ./scripts/setup.sh (non-interactive, ~5 min)"
  exit 1
fi
